# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PanoStreetView
                                 A QGIS plugin
 Allows pano street view
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-15
        copyright            : (C) 2024 by Sachin Kulal
        email                : sachinmk1998@gmail.com/sachin.k@aidash.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PanoStreetView class from file PanoStreetView.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .PanoStreetView import PanoStreetView
    return PanoStreetView(iface)
