# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\D-DRIVE\EDP\pannellum\Plugin\Test-1\panostreetview\PanoStreetView_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PanoStreetViewDockWidgetBase(object):
    def setupUi(self, PanoStreetViewDockWidgetBase):
        PanoStreetViewDockWidgetBase.setObjectName("PanoStreetViewDockWidgetBase")
        PanoStreetViewDockWidgetBase.resize(365, 268)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_shp = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_shp.setObjectName("le_shp")
        self.horizontalLayout.addWidget(self.le_shp)
        self.tb_shp = QtWidgets.QToolButton(self.dockWidgetContents)
        self.tb_shp.setObjectName("tb_shp")
        self.horizontalLayout.addWidget(self.tb_shp)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.le_img = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_img.setObjectName("le_img")
        self.horizontalLayout_2.addWidget(self.le_img)
        self.tb_img = QtWidgets.QToolButton(self.dockWidgetContents)
        self.tb_img.setObjectName("tb_img")
        self.horizontalLayout_2.addWidget(self.tb_img)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        PanoStreetViewDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(PanoStreetViewDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(PanoStreetViewDockWidgetBase)

    def retranslateUi(self, PanoStreetViewDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        PanoStreetViewDockWidgetBase.setWindowTitle(_translate("PanoStreetViewDockWidgetBase", "PanoStreetView"))
        self.label.setText(_translate("PanoStreetViewDockWidgetBase", "Path to Shapefile"))
        self.tb_shp.setText(_translate("PanoStreetViewDockWidgetBase", "..."))
        self.label_2.setText(_translate("PanoStreetViewDockWidgetBase", "Path to Images"))
        self.tb_img.setText(_translate("PanoStreetViewDockWidgetBase", "..."))
